# Generated by Django 4.1.1 on 2022-09-22 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_usermessage_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About section'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('position',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='chefs',
            options={'ordering': ('position',), 'verbose_name_plural': 'Chefs'},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ('position', 'price'), 'verbose_name_plural': 'Dishes'},
        ),
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ('position',), 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Gallery'},
        ),
        migrations.AlterModelOptions(
            name='ourinformation',
            options={'verbose_name_plural': 'Our information'},
        ),
        migrations.AlterModelOptions(
            name='testimonials',
            options={'ordering': ('position',), 'verbose_name_plural': 'Testimonials'},
        ),
        migrations.AlterModelOptions(
            name='titles',
            options={'verbose_name_plural': 'Titles'},
        ),
        migrations.AlterModelOptions(
            name='topsitepresentation',
            options={'ordering': ('position',), 'verbose_name_plural': 'Top site presentation'},
        ),
        migrations.AlterModelOptions(
            name='usermessage',
            options={'ordering': ('-date', '-is_processed'), 'verbose_name_plural': 'User messages'},
        ),
        migrations.AlterModelOptions(
            name='userreservation',
            options={'ordering': ('-date', '-is_processed'), 'verbose_name_plural': 'User reservations'},
        ),
        migrations.AlterModelOptions(
            name='whyus',
            options={'verbose_name_plural': '"Why us" section'},
        ),
    ]
